// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://devhvbltxwcdmotirwgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldmh2Ymx0eHdjZG1vdGlyd2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTIwMzcsImV4cCI6MjA2MjEyODAzN30.5RW2QR5mA0Cwfr6rd8zD3cSOMoLe4hCLEdJPuNTTdvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);